// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: stats_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RankingSource int32

const (
	RankingSource_SOURCE_ALL      RankingSource = 0
	RankingSource_SOURCE_HOT_LIST RankingSource = 1
)

// Enum value maps for RankingSource.
var (
	RankingSource_name = map[int32]string{
		0: "SOURCE_ALL",
		1: "SOURCE_HOT_LIST",
	}
	RankingSource_value = map[string]int32{
		"SOURCE_ALL":      0,
		"SOURCE_HOT_LIST": 1,
	}
)

func (x RankingSource) Enum() *RankingSource {
	p := new(RankingSource)
	*p = x
	return p
}

func (x RankingSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RankingSource) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_service_proto_enumTypes[0].Descriptor()
}

func (RankingSource) Type() protoreflect.EnumType {
	return &file_stats_service_proto_enumTypes[0]
}

func (x RankingSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RankingSource.Descriptor instead.
func (RankingSource) EnumDescriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{0}
}

type PositionDirection int32

const (
	PositionDirection_POSITION_ALL   PositionDirection = 0
	PositionDirection_POSITION_LONG  PositionDirection = 1
	PositionDirection_POSITION_SHORT PositionDirection = 2
)

// Enum value maps for PositionDirection.
var (
	PositionDirection_name = map[int32]string{
		0: "POSITION_ALL",
		1: "POSITION_LONG",
		2: "POSITION_SHORT",
	}
	PositionDirection_value = map[string]int32{
		"POSITION_ALL":   0,
		"POSITION_LONG":  1,
		"POSITION_SHORT": 2,
	}
)

func (x PositionDirection) Enum() *PositionDirection {
	p := new(PositionDirection)
	*p = x
	return p
}

func (x PositionDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_service_proto_enumTypes[1].Descriptor()
}

func (PositionDirection) Type() protoreflect.EnumType {
	return &file_stats_service_proto_enumTypes[1]
}

func (x PositionDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionDirection.Descriptor instead.
func (PositionDirection) EnumDescriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{1}
}

type TickerData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress       string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	PairAddress        string                 `protobuf:"bytes,2,opt,name=pair_address,json=pairAddress,proto3" json:"pair_address,omitempty"`
	Chain              string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	UpdateTime         int64                  `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	HolderDistribution *HolderDistribution    `protobuf:"bytes,5,opt,name=holder_distribution,json=holderDistribution,proto3,oneof" json:"holder_distribution,omitempty"` // 持有人分布
	MarketData         *MarketData            `protobuf:"bytes,6,opt,name=market_data,json=marketData,proto3,oneof" json:"market_data,omitempty"`                         // token市场概况数据
	TradingStats       *TradingStats          `protobuf:"bytes,7,opt,name=trading_stats,json=tradingStats,proto3,oneof" json:"trading_stats,omitempty"`                   // 交易统计
	TradeParams        *MMReport              `protobuf:"bytes,8,opt,name=trade_params,json=tradeParams,proto3,oneof" json:"trade_params,omitempty"`                      // 做多做空报告
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TickerData) Reset() {
	*x = TickerData{}
	mi := &file_stats_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickerData) ProtoMessage() {}

func (x *TickerData) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickerData.ProtoReflect.Descriptor instead.
func (*TickerData) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{0}
}

func (x *TickerData) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TickerData) GetPairAddress() string {
	if x != nil {
		return x.PairAddress
	}
	return ""
}

func (x *TickerData) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *TickerData) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *TickerData) GetHolderDistribution() *HolderDistribution {
	if x != nil {
		return x.HolderDistribution
	}
	return nil
}

func (x *TickerData) GetMarketData() *MarketData {
	if x != nil {
		return x.MarketData
	}
	return nil
}

func (x *TickerData) GetTradingStats() *TradingStats {
	if x != nil {
		return x.TradingStats
	}
	return nil
}

func (x *TickerData) GetTradeParams() *MMReport {
	if x != nil {
		return x.TradeParams
	}
	return nil
}

// 新增消息类型
type MMReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongLeverage  int32                  `protobuf:"varint,1,opt,name=long_leverage,json=longLeverage,proto3" json:"long_leverage,omitempty"`    // 做多报告
	ShortLeverage int32                  `protobuf:"varint,2,opt,name=short_leverage,json=shortLeverage,proto3" json:"short_leverage,omitempty"` // 做空报告
	ListingTime   int64                  `protobuf:"varint,3,opt,name=listing_time,json=listingTime,proto3" json:"listing_time,omitempty"`       // 上架时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MMReport) Reset() {
	*x = MMReport{}
	mi := &file_stats_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MMReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MMReport) ProtoMessage() {}

func (x *MMReport) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MMReport.ProtoReflect.Descriptor instead.
func (*MMReport) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{1}
}

func (x *MMReport) GetLongLeverage() int32 {
	if x != nil {
		return x.LongLeverage
	}
	return 0
}

func (x *MMReport) GetShortLeverage() int32 {
	if x != nil {
		return x.ShortLeverage
	}
	return 0
}

func (x *MMReport) GetListingTime() int64 {
	if x != nil {
		return x.ListingTime
	}
	return 0
}

// 持有人分布数据
type HolderDistribution struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HolderCount       int64                  `protobuf:"varint,1,opt,name=holder_count,json=holderCount,proto3" json:"holder_count,omitempty"`                     // 持有该token的地址总数
	Top_10HoldersRate float64                `protobuf:"fixed64,2,opt,name=top_10_holders_rate,json=top10HoldersRate,proto3" json:"top_10_holders_rate,omitempty"` // 前10持仓占比，百分比
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HolderDistribution) Reset() {
	*x = HolderDistribution{}
	mi := &file_stats_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderDistribution) ProtoMessage() {}

func (x *HolderDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderDistribution.ProtoReflect.Descriptor instead.
func (*HolderDistribution) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{2}
}

func (x *HolderDistribution) GetHolderCount() int64 {
	if x != nil {
		return x.HolderCount
	}
	return 0
}

func (x *HolderDistribution) GetTop_10HoldersRate() float64 {
	if x != nil {
		return x.Top_10HoldersRate
	}
	return 0
}

// token市场概况数据
type MarketData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MarketCap       float64                `protobuf:"fixed64,1,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`                  // 流通市值, circulating_supply * price
	Fdv             float64                `protobuf:"fixed64,2,opt,name=fdv,proto3" json:"fdv,omitempty"`                                               // 完全稀释市值, max_supply * price
	TotalSupply     string                 `protobuf:"bytes,3,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`              // 总供应量
	Liquidity       float64                `protobuf:"fixed64,4,opt,name=liquidity,proto3" json:"liquidity,omitempty"`                                   // 流动性
	Price           float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`                                           // 当前价格$
	Volume_24H      float64                `protobuf:"fixed64,6,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`                  // 24h成交额$
	PriceChange_24H float64                `protobuf:"fixed64,7,opt,name=price_change_24h,json=priceChange24h,proto3" json:"price_change_24h,omitempty"` // 24h价格变化百分比
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarketData) Reset() {
	*x = MarketData{}
	mi := &file_stats_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketData) ProtoMessage() {}

func (x *MarketData) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketData.ProtoReflect.Descriptor instead.
func (*MarketData) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{3}
}

func (x *MarketData) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *MarketData) GetFdv() float64 {
	if x != nil {
		return x.Fdv
	}
	return 0
}

func (x *MarketData) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *MarketData) GetLiquidity() float64 {
	if x != nil {
		return x.Liquidity
	}
	return 0
}

func (x *MarketData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketData) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *MarketData) GetPriceChange_24H() float64 {
	if x != nil {
		return x.PriceChange_24H
	}
	return 0
}

// 交易统计数据
type TradingStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PriceChange_1M  float64                `protobuf:"fixed64,1,opt,name=price_change_1m,json=priceChange1m,proto3" json:"price_change_1m,omitempty"`    // 1m价格变化百分比
	PriceChange_5M  float64                `protobuf:"fixed64,2,opt,name=price_change_5m,json=priceChange5m,proto3" json:"price_change_5m,omitempty"`    // 5m价格变化百分比
	PriceChange_1H  float64                `protobuf:"fixed64,3,opt,name=price_change_1h,json=priceChange1h,proto3" json:"price_change_1h,omitempty"`    // 1h价格变化百分比
	PriceChange_6H  float64                `protobuf:"fixed64,4,opt,name=price_change_6h,json=priceChange6h,proto3" json:"price_change_6h,omitempty"`    // 6h价格变化百分比
	PriceChange_24H float64                `protobuf:"fixed64,5,opt,name=price_change_24h,json=priceChange24h,proto3" json:"price_change_24h,omitempty"` // 24h价格变化百分比
	Buys_1M         uint32                 `protobuf:"varint,6,opt,name=buys_1m,json=buys1m,proto3" json:"buys_1m,omitempty"`                            // 1m买入笔数
	Buys_5M         uint32                 `protobuf:"varint,7,opt,name=buys_5m,json=buys5m,proto3" json:"buys_5m,omitempty"`                            // 5m买入笔数
	Buys_1H         uint32                 `protobuf:"varint,8,opt,name=buys_1h,json=buys1h,proto3" json:"buys_1h,omitempty"`                            // 1h买入笔数
	Buys_6H         uint32                 `protobuf:"varint,9,opt,name=buys_6h,json=buys6h,proto3" json:"buys_6h,omitempty"`                            // 6h买入笔数
	Buys_24H        uint32                 `protobuf:"varint,10,opt,name=buys_24h,json=buys24h,proto3" json:"buys_24h,omitempty"`                        // 24h买入笔数
	Sells_1M        uint32                 `protobuf:"varint,11,opt,name=sells_1m,json=sells1m,proto3" json:"sells_1m,omitempty"`                        // 1m卖出笔数
	Sells_5M        uint32                 `protobuf:"varint,12,opt,name=sells_5m,json=sells5m,proto3" json:"sells_5m,omitempty"`                        // 5m卖出笔数
	Sells_1H        uint32                 `protobuf:"varint,13,opt,name=sells_1h,json=sells1h,proto3" json:"sells_1h,omitempty"`                        // 1h卖出笔数
	Sells_6H        uint32                 `protobuf:"varint,14,opt,name=sells_6h,json=sells6h,proto3" json:"sells_6h,omitempty"`                        // 6h卖出笔数
	Sells_24H       uint32                 `protobuf:"varint,15,opt,name=sells_24h,json=sells24h,proto3" json:"sells_24h,omitempty"`                     // 24h卖出笔数
	TotalTrades_1M  uint32                 `protobuf:"varint,16,opt,name=total_trades_1m,json=totalTrades1m,proto3" json:"total_trades_1m,omitempty"`    // 1m总交易笔数
	TotalTrades_5M  uint32                 `protobuf:"varint,17,opt,name=total_trades_5m,json=totalTrades5m,proto3" json:"total_trades_5m,omitempty"`    // 5m总交易笔数
	TotalTrades_1H  uint32                 `protobuf:"varint,18,opt,name=total_trades_1h,json=totalTrades1h,proto3" json:"total_trades_1h,omitempty"`    // 1h总交易笔数
	TotalTrades_6H  uint32                 `protobuf:"varint,19,opt,name=total_trades_6h,json=totalTrades6h,proto3" json:"total_trades_6h,omitempty"`    // 6h总交易笔数
	TotalTrades_24H uint32                 `protobuf:"varint,20,opt,name=total_trades_24h,json=totalTrades24h,proto3" json:"total_trades_24h,omitempty"` // 24h总交易笔数
	Volume_1M       float64                `protobuf:"fixed64,21,opt,name=volume_1m,json=volume1m,proto3" json:"volume_1m,omitempty"`                    // 1m总成交额$
	Volume_5M       float64                `protobuf:"fixed64,22,opt,name=volume_5m,json=volume5m,proto3" json:"volume_5m,omitempty"`                    // 5m总成交额$
	Volume_1H       float64                `protobuf:"fixed64,23,opt,name=volume_1h,json=volume1h,proto3" json:"volume_1h,omitempty"`                    // 1h总成交额$
	Volume_6H       float64                `protobuf:"fixed64,24,opt,name=volume_6h,json=volume6h,proto3" json:"volume_6h,omitempty"`                    // 6h总成交额$
	Volume_24H      float64                `protobuf:"fixed64,25,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`                 // 24h总成交额$
	BuyVolume_1M    float64                `protobuf:"fixed64,26,opt,name=buy_volume_1m,json=buyVolume1m,proto3" json:"buy_volume_1m,omitempty"`         // 1m买入成交额$
	BuyVolume_5M    float64                `protobuf:"fixed64,27,opt,name=buy_volume_5m,json=buyVolume5m,proto3" json:"buy_volume_5m,omitempty"`         // 5m买入成交额$
	BuyVolume_1H    float64                `protobuf:"fixed64,28,opt,name=buy_volume_1h,json=buyVolume1h,proto3" json:"buy_volume_1h,omitempty"`         // 1h买入成交额$
	BuyVolume_6H    float64                `protobuf:"fixed64,29,opt,name=buy_volume_6h,json=buyVolume6h,proto3" json:"buy_volume_6h,omitempty"`         // 6h买入成交额$
	BuyVolume_24H   float64                `protobuf:"fixed64,30,opt,name=buy_volume_24h,json=buyVolume24h,proto3" json:"buy_volume_24h,omitempty"`      // 24h买入成交额$
	SellVolume_1M   float64                `protobuf:"fixed64,31,opt,name=sell_volume_1m,json=sellVolume1m,proto3" json:"sell_volume_1m,omitempty"`      // 1m卖出成交额$
	SellVolume_5M   float64                `protobuf:"fixed64,32,opt,name=sell_volume_5m,json=sellVolume5m,proto3" json:"sell_volume_5m,omitempty"`      // 5m卖出成交额$
	SellVolume_1H   float64                `protobuf:"fixed64,33,opt,name=sell_volume_1h,json=sellVolume1h,proto3" json:"sell_volume_1h,omitempty"`      // 1h卖出成交额$
	SellVolume_6H   float64                `protobuf:"fixed64,34,opt,name=sell_volume_6h,json=sellVolume6h,proto3" json:"sell_volume_6h,omitempty"`      // 6h卖出成交额$
	SellVolume_24H  float64                `protobuf:"fixed64,35,opt,name=sell_volume_24h,json=sellVolume24h,proto3" json:"sell_volume_24h,omitempty"`   // 24h卖出成交额$
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TradingStats) Reset() {
	*x = TradingStats{}
	mi := &file_stats_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradingStats) ProtoMessage() {}

func (x *TradingStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradingStats.ProtoReflect.Descriptor instead.
func (*TradingStats) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{4}
}

func (x *TradingStats) GetPriceChange_1M() float64 {
	if x != nil {
		return x.PriceChange_1M
	}
	return 0
}

func (x *TradingStats) GetPriceChange_5M() float64 {
	if x != nil {
		return x.PriceChange_5M
	}
	return 0
}

func (x *TradingStats) GetPriceChange_1H() float64 {
	if x != nil {
		return x.PriceChange_1H
	}
	return 0
}

func (x *TradingStats) GetPriceChange_6H() float64 {
	if x != nil {
		return x.PriceChange_6H
	}
	return 0
}

func (x *TradingStats) GetPriceChange_24H() float64 {
	if x != nil {
		return x.PriceChange_24H
	}
	return 0
}

func (x *TradingStats) GetBuys_1M() uint32 {
	if x != nil {
		return x.Buys_1M
	}
	return 0
}

func (x *TradingStats) GetBuys_5M() uint32 {
	if x != nil {
		return x.Buys_5M
	}
	return 0
}

func (x *TradingStats) GetBuys_1H() uint32 {
	if x != nil {
		return x.Buys_1H
	}
	return 0
}

func (x *TradingStats) GetBuys_6H() uint32 {
	if x != nil {
		return x.Buys_6H
	}
	return 0
}

func (x *TradingStats) GetBuys_24H() uint32 {
	if x != nil {
		return x.Buys_24H
	}
	return 0
}

func (x *TradingStats) GetSells_1M() uint32 {
	if x != nil {
		return x.Sells_1M
	}
	return 0
}

func (x *TradingStats) GetSells_5M() uint32 {
	if x != nil {
		return x.Sells_5M
	}
	return 0
}

func (x *TradingStats) GetSells_1H() uint32 {
	if x != nil {
		return x.Sells_1H
	}
	return 0
}

func (x *TradingStats) GetSells_6H() uint32 {
	if x != nil {
		return x.Sells_6H
	}
	return 0
}

func (x *TradingStats) GetSells_24H() uint32 {
	if x != nil {
		return x.Sells_24H
	}
	return 0
}

func (x *TradingStats) GetTotalTrades_1M() uint32 {
	if x != nil {
		return x.TotalTrades_1M
	}
	return 0
}

func (x *TradingStats) GetTotalTrades_5M() uint32 {
	if x != nil {
		return x.TotalTrades_5M
	}
	return 0
}

func (x *TradingStats) GetTotalTrades_1H() uint32 {
	if x != nil {
		return x.TotalTrades_1H
	}
	return 0
}

func (x *TradingStats) GetTotalTrades_6H() uint32 {
	if x != nil {
		return x.TotalTrades_6H
	}
	return 0
}

func (x *TradingStats) GetTotalTrades_24H() uint32 {
	if x != nil {
		return x.TotalTrades_24H
	}
	return 0
}

func (x *TradingStats) GetVolume_1M() float64 {
	if x != nil {
		return x.Volume_1M
	}
	return 0
}

func (x *TradingStats) GetVolume_5M() float64 {
	if x != nil {
		return x.Volume_5M
	}
	return 0
}

func (x *TradingStats) GetVolume_1H() float64 {
	if x != nil {
		return x.Volume_1H
	}
	return 0
}

func (x *TradingStats) GetVolume_6H() float64 {
	if x != nil {
		return x.Volume_6H
	}
	return 0
}

func (x *TradingStats) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *TradingStats) GetBuyVolume_1M() float64 {
	if x != nil {
		return x.BuyVolume_1M
	}
	return 0
}

func (x *TradingStats) GetBuyVolume_5M() float64 {
	if x != nil {
		return x.BuyVolume_5M
	}
	return 0
}

func (x *TradingStats) GetBuyVolume_1H() float64 {
	if x != nil {
		return x.BuyVolume_1H
	}
	return 0
}

func (x *TradingStats) GetBuyVolume_6H() float64 {
	if x != nil {
		return x.BuyVolume_6H
	}
	return 0
}

func (x *TradingStats) GetBuyVolume_24H() float64 {
	if x != nil {
		return x.BuyVolume_24H
	}
	return 0
}

func (x *TradingStats) GetSellVolume_1M() float64 {
	if x != nil {
		return x.SellVolume_1M
	}
	return 0
}

func (x *TradingStats) GetSellVolume_5M() float64 {
	if x != nil {
		return x.SellVolume_5M
	}
	return 0
}

func (x *TradingStats) GetSellVolume_1H() float64 {
	if x != nil {
		return x.SellVolume_1H
	}
	return 0
}

func (x *TradingStats) GetSellVolume_6H() float64 {
	if x != nil {
		return x.SellVolume_6H
	}
	return 0
}

func (x *TradingStats) GetSellVolume_24H() float64 {
	if x != nil {
		return x.SellVolume_24H
	}
	return 0
}

type GetRankingListRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RankType          int32                  `protobuf:"varint,1,opt,name=rank_type,json=rankType,proto3" json:"rank_type,omitempty"`                            // 1:热门合约 2:热门币
	PositionDirection int32                  `protobuf:"varint,2,opt,name=position_direction,json=positionDirection,proto3" json:"position_direction,omitempty"` // 0:多和空 1:多 2:空; 热门币随便填
	TimeFrame         string                 `protobuf:"bytes,3,opt,name=time_frame,json=timeFrame,proto3" json:"time_frame,omitempty"`                          // 时间窗口: 1m、5m、1h、6h、24h, 全局排序字段随便填
	SortBy            string                 `protobuf:"bytes,4,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`                                   // 排序字段: market、fdv、liquidity、price_change、volume、total_trades、listing_time
	SortOrder         string                 `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`                          // 排序方向: asc、desc
	PageNum           int32                  `protobuf:"varint,6,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`                               // 第几页,默认1
	PageSize          int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                            // 每页多少条,默认100
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRankingListRequest) Reset() {
	*x = GetRankingListRequest{}
	mi := &file_stats_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingListRequest) ProtoMessage() {}

func (x *GetRankingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingListRequest.ProtoReflect.Descriptor instead.
func (*GetRankingListRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetRankingListRequest) GetRankType() int32 {
	if x != nil {
		return x.RankType
	}
	return 0
}

func (x *GetRankingListRequest) GetPositionDirection() int32 {
	if x != nil {
		return x.PositionDirection
	}
	return 0
}

func (x *GetRankingListRequest) GetTimeFrame() string {
	if x != nil {
		return x.TimeFrame
	}
	return ""
}

func (x *GetRankingListRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetRankingListRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *GetRankingListRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetRankingListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetRankingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranking       []*TickerData          `protobuf:"bytes,1,rep,name=ranking,proto3" json:"ranking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingListResponse) Reset() {
	*x = GetRankingListResponse{}
	mi := &file_stats_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingListResponse) ProtoMessage() {}

func (x *GetRankingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingListResponse.ProtoReflect.Descriptor instead.
func (*GetRankingListResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetRankingListResponse) GetRanking() []*TickerData {
	if x != nil {
		return x.Ranking
	}
	return nil
}

type GetTickersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairAddresses []string               `protobuf:"bytes,1,rep,name=pair_addresses,json=pairAddresses,proto3" json:"pair_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickersRequest) Reset() {
	*x = GetTickersRequest{}
	mi := &file_stats_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickersRequest) ProtoMessage() {}

func (x *GetTickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickersRequest.ProtoReflect.Descriptor instead.
func (*GetTickersRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTickersRequest) GetPairAddresses() []string {
	if x != nil {
		return x.PairAddresses
	}
	return nil
}

type GetTickersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*TickerData          `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickersResponse) Reset() {
	*x = GetTickersResponse{}
	mi := &file_stats_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickersResponse) ProtoMessage() {}

func (x *GetTickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickersResponse.ProtoReflect.Descriptor instead.
func (*GetTickersResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTickersResponse) GetTickers() []*TickerData {
	if x != nil {
		return x.Tickers
	}
	return nil
}

type GetQuotePriceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuoteAddresses []string               `protobuf:"bytes,1,rep,name=quote_addresses,json=quoteAddresses,proto3" json:"quote_addresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQuotePriceRequest) Reset() {
	*x = GetQuotePriceRequest{}
	mi := &file_stats_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotePriceRequest) ProtoMessage() {}

func (x *GetQuotePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotePriceRequest.ProtoReflect.Descriptor instead.
func (*GetQuotePriceRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetQuotePriceRequest) GetQuoteAddresses() []string {
	if x != nil {
		return x.QuoteAddresses
	}
	return nil
}

type QuotePrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteAddress  string                 `protobuf:"bytes,1,opt,name=quote_address,json=quoteAddress,proto3" json:"quote_address,omitempty"`
	PriceUsd      float64                `protobuf:"fixed64,2,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	Decimals      uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Valid         bool                   `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotePrice) Reset() {
	*x = QuotePrice{}
	mi := &file_stats_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotePrice) ProtoMessage() {}

func (x *QuotePrice) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotePrice.ProtoReflect.Descriptor instead.
func (*QuotePrice) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{10}
}

func (x *QuotePrice) GetQuoteAddress() string {
	if x != nil {
		return x.QuoteAddress
	}
	return ""
}

func (x *QuotePrice) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *QuotePrice) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *QuotePrice) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type GetQuotePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*QuotePrice          `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuotePriceResponse) Reset() {
	*x = GetQuotePriceResponse{}
	mi := &file_stats_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuotePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotePriceResponse) ProtoMessage() {}

func (x *GetQuotePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotePriceResponse.ProtoReflect.Descriptor instead.
func (*GetQuotePriceResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetQuotePriceResponse) GetPrices() []*QuotePrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

type GetStatsByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsByTokenRequest) Reset() {
	*x = GetStatsByTokenRequest{}
	mi := &file_stats_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsByTokenRequest) ProtoMessage() {}

func (x *GetStatsByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsByTokenRequest.ProtoReflect.Descriptor instead.
func (*GetStatsByTokenRequest) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatsByTokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type TokenStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress       string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	HolderDistribution *HolderDistribution    `protobuf:"bytes,2,opt,name=holder_distribution,json=holderDistribution,proto3,oneof" json:"holder_distribution,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TokenStats) Reset() {
	*x = TokenStats{}
	mi := &file_stats_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenStats) ProtoMessage() {}

func (x *TokenStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenStats.ProtoReflect.Descriptor instead.
func (*TokenStats) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{13}
}

func (x *TokenStats) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TokenStats) GetHolderDistribution() *HolderDistribution {
	if x != nil {
		return x.HolderDistribution
	}
	return nil
}

type GetStatsByTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *TokenStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsByTokenResponse) Reset() {
	*x = GetStatsByTokenResponse{}
	mi := &file_stats_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsByTokenResponse) ProtoMessage() {}

func (x *GetStatsByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsByTokenResponse.ProtoReflect.Descriptor instead.
func (*GetStatsByTokenResponse) Descriptor() ([]byte, []int) {
	return file_stats_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatsByTokenResponse) GetStats() *TokenStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_stats_service_proto protoreflect.FileDescriptor

const file_stats_service_proto_rawDesc = "" +
	"\n" +
	"\x13stats_service.proto\x12\x02pb\"\xcc\x03\n" +
	"\n" +
	"TickerData\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12!\n" +
	"\fpair_address\x18\x02 \x01(\tR\vpairAddress\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\x12\x1f\n" +
	"\vupdate_time\x18\x04 \x01(\x03R\n" +
	"updateTime\x12L\n" +
	"\x13holder_distribution\x18\x05 \x01(\v2\x16.pb.HolderDistributionH\x00R\x12holderDistribution\x88\x01\x01\x124\n" +
	"\vmarket_data\x18\x06 \x01(\v2\x0e.pb.MarketDataH\x01R\n" +
	"marketData\x88\x01\x01\x12:\n" +
	"\rtrading_stats\x18\a \x01(\v2\x10.pb.TradingStatsH\x02R\ftradingStats\x88\x01\x01\x124\n" +
	"\ftrade_params\x18\b \x01(\v2\f.pb.MMReportH\x03R\vtradeParams\x88\x01\x01B\x16\n" +
	"\x14_holder_distributionB\x0e\n" +
	"\f_market_dataB\x10\n" +
	"\x0e_trading_statsB\x0f\n" +
	"\r_trade_params\"y\n" +
	"\bMMReport\x12#\n" +
	"\rlong_leverage\x18\x01 \x01(\x05R\flongLeverage\x12%\n" +
	"\x0eshort_leverage\x18\x02 \x01(\x05R\rshortLeverage\x12!\n" +
	"\flisting_time\x18\x03 \x01(\x03R\vlistingTime\"f\n" +
	"\x12HolderDistribution\x12!\n" +
	"\fholder_count\x18\x01 \x01(\x03R\vholderCount\x12-\n" +
	"\x13top_10_holders_rate\x18\x02 \x01(\x01R\x10top10HoldersRate\"\xdd\x01\n" +
	"\n" +
	"MarketData\x12\x1d\n" +
	"\n" +
	"market_cap\x18\x01 \x01(\x01R\tmarketCap\x12\x10\n" +
	"\x03fdv\x18\x02 \x01(\x01R\x03fdv\x12!\n" +
	"\ftotal_supply\x18\x03 \x01(\tR\vtotalSupply\x12\x1c\n" +
	"\tliquidity\x18\x04 \x01(\x01R\tliquidity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x06 \x01(\x01R\tvolume24h\x12(\n" +
	"\x10price_change_24h\x18\a \x01(\x01R\x0epriceChange24h\"\xb3\t\n" +
	"\fTradingStats\x12&\n" +
	"\x0fprice_change_1m\x18\x01 \x01(\x01R\rpriceChange1m\x12&\n" +
	"\x0fprice_change_5m\x18\x02 \x01(\x01R\rpriceChange5m\x12&\n" +
	"\x0fprice_change_1h\x18\x03 \x01(\x01R\rpriceChange1h\x12&\n" +
	"\x0fprice_change_6h\x18\x04 \x01(\x01R\rpriceChange6h\x12(\n" +
	"\x10price_change_24h\x18\x05 \x01(\x01R\x0epriceChange24h\x12\x17\n" +
	"\abuys_1m\x18\x06 \x01(\rR\x06buys1m\x12\x17\n" +
	"\abuys_5m\x18\a \x01(\rR\x06buys5m\x12\x17\n" +
	"\abuys_1h\x18\b \x01(\rR\x06buys1h\x12\x17\n" +
	"\abuys_6h\x18\t \x01(\rR\x06buys6h\x12\x19\n" +
	"\bbuys_24h\x18\n" +
	" \x01(\rR\abuys24h\x12\x19\n" +
	"\bsells_1m\x18\v \x01(\rR\asells1m\x12\x19\n" +
	"\bsells_5m\x18\f \x01(\rR\asells5m\x12\x19\n" +
	"\bsells_1h\x18\r \x01(\rR\asells1h\x12\x19\n" +
	"\bsells_6h\x18\x0e \x01(\rR\asells6h\x12\x1b\n" +
	"\tsells_24h\x18\x0f \x01(\rR\bsells24h\x12&\n" +
	"\x0ftotal_trades_1m\x18\x10 \x01(\rR\rtotalTrades1m\x12&\n" +
	"\x0ftotal_trades_5m\x18\x11 \x01(\rR\rtotalTrades5m\x12&\n" +
	"\x0ftotal_trades_1h\x18\x12 \x01(\rR\rtotalTrades1h\x12&\n" +
	"\x0ftotal_trades_6h\x18\x13 \x01(\rR\rtotalTrades6h\x12(\n" +
	"\x10total_trades_24h\x18\x14 \x01(\rR\x0etotalTrades24h\x12\x1b\n" +
	"\tvolume_1m\x18\x15 \x01(\x01R\bvolume1m\x12\x1b\n" +
	"\tvolume_5m\x18\x16 \x01(\x01R\bvolume5m\x12\x1b\n" +
	"\tvolume_1h\x18\x17 \x01(\x01R\bvolume1h\x12\x1b\n" +
	"\tvolume_6h\x18\x18 \x01(\x01R\bvolume6h\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x19 \x01(\x01R\tvolume24h\x12\"\n" +
	"\rbuy_volume_1m\x18\x1a \x01(\x01R\vbuyVolume1m\x12\"\n" +
	"\rbuy_volume_5m\x18\x1b \x01(\x01R\vbuyVolume5m\x12\"\n" +
	"\rbuy_volume_1h\x18\x1c \x01(\x01R\vbuyVolume1h\x12\"\n" +
	"\rbuy_volume_6h\x18\x1d \x01(\x01R\vbuyVolume6h\x12$\n" +
	"\x0ebuy_volume_24h\x18\x1e \x01(\x01R\fbuyVolume24h\x12$\n" +
	"\x0esell_volume_1m\x18\x1f \x01(\x01R\fsellVolume1m\x12$\n" +
	"\x0esell_volume_5m\x18  \x01(\x01R\fsellVolume5m\x12$\n" +
	"\x0esell_volume_1h\x18! \x01(\x01R\fsellVolume1h\x12$\n" +
	"\x0esell_volume_6h\x18\" \x01(\x01R\fsellVolume6h\x12&\n" +
	"\x0fsell_volume_24h\x18# \x01(\x01R\rsellVolume24h\"\xf2\x01\n" +
	"\x15GetRankingListRequest\x12\x1b\n" +
	"\trank_type\x18\x01 \x01(\x05R\brankType\x12-\n" +
	"\x12position_direction\x18\x02 \x01(\x05R\x11positionDirection\x12\x1d\n" +
	"\n" +
	"time_frame\x18\x03 \x01(\tR\ttimeFrame\x12\x17\n" +
	"\asort_by\x18\x04 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tR\tsortOrder\x12\x19\n" +
	"\bpage_num\x18\x06 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"B\n" +
	"\x16GetRankingListResponse\x12(\n" +
	"\aranking\x18\x01 \x03(\v2\x0e.pb.TickerDataR\aranking\":\n" +
	"\x11GetTickersRequest\x12%\n" +
	"\x0epair_addresses\x18\x01 \x03(\tR\rpairAddresses\">\n" +
	"\x12GetTickersResponse\x12(\n" +
	"\atickers\x18\x01 \x03(\v2\x0e.pb.TickerDataR\atickers\"?\n" +
	"\x14GetQuotePriceRequest\x12'\n" +
	"\x0fquote_addresses\x18\x01 \x03(\tR\x0equoteAddresses\"\x80\x01\n" +
	"\n" +
	"QuotePrice\x12#\n" +
	"\rquote_address\x18\x01 \x01(\tR\fquoteAddress\x12\x1b\n" +
	"\tprice_usd\x18\x02 \x01(\x01R\bpriceUsd\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12\x14\n" +
	"\x05valid\x18\x04 \x01(\bR\x05valid\"?\n" +
	"\x15GetQuotePriceResponse\x12&\n" +
	"\x06prices\x18\x01 \x03(\v2\x0e.pb.QuotePriceR\x06prices\"=\n" +
	"\x16GetStatsByTokenRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\"\x97\x01\n" +
	"\n" +
	"TokenStats\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\x12L\n" +
	"\x13holder_distribution\x18\x02 \x01(\v2\x16.pb.HolderDistributionH\x00R\x12holderDistribution\x88\x01\x01B\x16\n" +
	"\x14_holder_distribution\"?\n" +
	"\x17GetStatsByTokenResponse\x12$\n" +
	"\x05stats\x18\x01 \x01(\v2\x0e.pb.TokenStatsR\x05stats*4\n" +
	"\rRankingSource\x12\x0e\n" +
	"\n" +
	"SOURCE_ALL\x10\x00\x12\x13\n" +
	"\x0fSOURCE_HOT_LIST\x10\x01*L\n" +
	"\x11PositionDirection\x12\x10\n" +
	"\fPOSITION_ALL\x10\x00\x12\x11\n" +
	"\rPOSITION_LONG\x10\x01\x12\x12\n" +
	"\x0ePOSITION_SHORT\x10\x022\xac\x02\n" +
	"\x11StatsQueryService\x12G\n" +
	"\x0eGetRankingList\x12\x19.pb.GetRankingListRequest\x1a\x1a.pb.GetRankingListResponse\x12;\n" +
	"\n" +
	"GetTickers\x12\x15.pb.GetTickersRequest\x1a\x16.pb.GetTickersResponse\x12J\n" +
	"\x0fGetStatsByToken\x12\x1a.pb.GetStatsByTokenRequest\x1a\x1b.pb.GetStatsByTokenResponse\x12E\n" +
	"\x0eGetQuotePrices\x12\x18.pb.GetQuotePriceRequest\x1a\x19.pb.GetQuotePriceResponseB\x15Z\x13dex-stats-sol/pb;pbb\x06proto3"

var (
	file_stats_service_proto_rawDescOnce sync.Once
	file_stats_service_proto_rawDescData []byte
)

func file_stats_service_proto_rawDescGZIP() []byte {
	file_stats_service_proto_rawDescOnce.Do(func() {
		file_stats_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_service_proto_rawDesc), len(file_stats_service_proto_rawDesc)))
	})
	return file_stats_service_proto_rawDescData
}

var file_stats_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stats_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_stats_service_proto_goTypes = []any{
	(RankingSource)(0),              // 0: pb.RankingSource
	(PositionDirection)(0),          // 1: pb.PositionDirection
	(*TickerData)(nil),              // 2: pb.TickerData
	(*MMReport)(nil),                // 3: pb.MMReport
	(*HolderDistribution)(nil),      // 4: pb.HolderDistribution
	(*MarketData)(nil),              // 5: pb.MarketData
	(*TradingStats)(nil),            // 6: pb.TradingStats
	(*GetRankingListRequest)(nil),   // 7: pb.GetRankingListRequest
	(*GetRankingListResponse)(nil),  // 8: pb.GetRankingListResponse
	(*GetTickersRequest)(nil),       // 9: pb.GetTickersRequest
	(*GetTickersResponse)(nil),      // 10: pb.GetTickersResponse
	(*GetQuotePriceRequest)(nil),    // 11: pb.GetQuotePriceRequest
	(*QuotePrice)(nil),              // 12: pb.QuotePrice
	(*GetQuotePriceResponse)(nil),   // 13: pb.GetQuotePriceResponse
	(*GetStatsByTokenRequest)(nil),  // 14: pb.GetStatsByTokenRequest
	(*TokenStats)(nil),              // 15: pb.TokenStats
	(*GetStatsByTokenResponse)(nil), // 16: pb.GetStatsByTokenResponse
}
var file_stats_service_proto_depIdxs = []int32{
	4,  // 0: pb.TickerData.holder_distribution:type_name -> pb.HolderDistribution
	5,  // 1: pb.TickerData.market_data:type_name -> pb.MarketData
	6,  // 2: pb.TickerData.trading_stats:type_name -> pb.TradingStats
	3,  // 3: pb.TickerData.trade_params:type_name -> pb.MMReport
	2,  // 4: pb.GetRankingListResponse.ranking:type_name -> pb.TickerData
	2,  // 5: pb.GetTickersResponse.tickers:type_name -> pb.TickerData
	12, // 6: pb.GetQuotePriceResponse.prices:type_name -> pb.QuotePrice
	4,  // 7: pb.TokenStats.holder_distribution:type_name -> pb.HolderDistribution
	15, // 8: pb.GetStatsByTokenResponse.stats:type_name -> pb.TokenStats
	7,  // 9: pb.StatsQueryService.GetRankingList:input_type -> pb.GetRankingListRequest
	9,  // 10: pb.StatsQueryService.GetTickers:input_type -> pb.GetTickersRequest
	14, // 11: pb.StatsQueryService.GetStatsByToken:input_type -> pb.GetStatsByTokenRequest
	11, // 12: pb.StatsQueryService.GetQuotePrices:input_type -> pb.GetQuotePriceRequest
	8,  // 13: pb.StatsQueryService.GetRankingList:output_type -> pb.GetRankingListResponse
	10, // 14: pb.StatsQueryService.GetTickers:output_type -> pb.GetTickersResponse
	16, // 15: pb.StatsQueryService.GetStatsByToken:output_type -> pb.GetStatsByTokenResponse
	13, // 16: pb.StatsQueryService.GetQuotePrices:output_type -> pb.GetQuotePriceResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_stats_service_proto_init() }
func file_stats_service_proto_init() {
	if File_stats_service_proto != nil {
		return
	}
	file_stats_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_stats_service_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_service_proto_rawDesc), len(file_stats_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_service_proto_goTypes,
		DependencyIndexes: file_stats_service_proto_depIdxs,
		EnumInfos:         file_stats_service_proto_enumTypes,
		MessageInfos:      file_stats_service_proto_msgTypes,
	}.Build()
	File_stats_service_proto = out.File
	file_stats_service_proto_goTypes = nil
	file_stats_service_proto_depIdxs = nil
}
