// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: tokenmeta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SupplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  []string               `protobuf:"bytes,1,rep,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyRequest) Reset() {
	*x = SupplyRequest{}
	mi := &file_tokenmeta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyRequest) ProtoMessage() {}

func (x *SupplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyRequest.ProtoReflect.Descriptor instead.
func (*SupplyRequest) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{0}
}

func (x *SupplyRequest) GetTokenAddress() []string {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

type SupplyInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress      []byte                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Symbol            string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals          uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	TotalSupply       string                 `protobuf:"bytes,4,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	MaxSupply         string                 `protobuf:"bytes,5,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	CirculatingSupply string                 `protobuf:"bytes,6,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	Icon              string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Name              string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SupplyInfo) Reset() {
	*x = SupplyInfo{}
	mi := &file_tokenmeta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyInfo) ProtoMessage() {}

func (x *SupplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyInfo.ProtoReflect.Descriptor instead.
func (*SupplyInfo) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{1}
}

func (x *SupplyInfo) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *SupplyInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SupplyInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *SupplyInfo) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *SupplyInfo) GetMaxSupply() string {
	if x != nil {
		return x.MaxSupply
	}
	return ""
}

func (x *SupplyInfo) GetCirculatingSupply() string {
	if x != nil {
		return x.CirculatingSupply
	}
	return ""
}

func (x *SupplyInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *SupplyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SupplyInfos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*SupplyInfo          `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyInfos) Reset() {
	*x = SupplyInfos{}
	mi := &file_tokenmeta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyInfos) ProtoMessage() {}

func (x *SupplyInfos) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyInfos.ProtoReflect.Descriptor instead.
func (*SupplyInfos) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{2}
}

func (x *SupplyInfos) GetInfos() []*SupplyInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_tokenmeta_proto protoreflect.FileDescriptor

const file_tokenmeta_proto_rawDesc = "" +
	"\n" +
	"\x0ftokenmeta.proto\x12\bmetadata\"4\n" +
	"\rSupplyRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x03(\tR\ftokenAddress\"\xfe\x01\n" +
	"\n" +
	"SupplyInfo\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\fR\ftokenAddress\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x04 \x01(\tR\vtotalSupply\x12\x1d\n" +
	"\n" +
	"max_supply\x18\x05 \x01(\tR\tmaxSupply\x12-\n" +
	"\x12circulating_supply\x18\x06 \x01(\tR\x11circulatingSupply\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\"9\n" +
	"\vSupplyInfos\x12*\n" +
	"\x05infos\x18\x01 \x03(\v2\x14.metadata.SupplyInfoR\x05infos2U\n" +
	"\bMetadata\x12I\n" +
	"\x17GetTokenSupplyByAddress\x12\x17.metadata.SupplyRequest\x1a\x15.metadata.SupplyInfosB\x15Z\x13dex-stats-sol/pb;pbb\x06proto3"

var (
	file_tokenmeta_proto_rawDescOnce sync.Once
	file_tokenmeta_proto_rawDescData []byte
)

func file_tokenmeta_proto_rawDescGZIP() []byte {
	file_tokenmeta_proto_rawDescOnce.Do(func() {
		file_tokenmeta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokenmeta_proto_rawDesc), len(file_tokenmeta_proto_rawDesc)))
	})
	return file_tokenmeta_proto_rawDescData
}

var file_tokenmeta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tokenmeta_proto_goTypes = []any{
	(*SupplyRequest)(nil), // 0: metadata.SupplyRequest
	(*SupplyInfo)(nil),    // 1: metadata.SupplyInfo
	(*SupplyInfos)(nil),   // 2: metadata.SupplyInfos
}
var file_tokenmeta_proto_depIdxs = []int32{
	1, // 0: metadata.SupplyInfos.infos:type_name -> metadata.SupplyInfo
	0, // 1: metadata.Metadata.GetTokenSupplyByAddress:input_type -> metadata.SupplyRequest
	2, // 2: metadata.Metadata.GetTokenSupplyByAddress:output_type -> metadata.SupplyInfos
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tokenmeta_proto_init() }
func file_tokenmeta_proto_init() {
	if File_tokenmeta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokenmeta_proto_rawDesc), len(file_tokenmeta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokenmeta_proto_goTypes,
		DependencyIndexes: file_tokenmeta_proto_depIdxs,
		MessageInfos:      file_tokenmeta_proto_msgTypes,
	}.Build()
	File_tokenmeta_proto = out.File
	file_tokenmeta_proto_goTypes = nil
	file_tokenmeta_proto_depIdxs = nil
}
