// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: tokenmeta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTokenAndMetaByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  string                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenAndMetaByAddressRequest) Reset() {
	*x = GetTokenAndMetaByAddressRequest{}
	mi := &file_tokenmeta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenAndMetaByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenAndMetaByAddressRequest) ProtoMessage() {}

func (x *GetTokenAndMetaByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenAndMetaByAddressRequest.ProtoReflect.Descriptor instead.
func (*GetTokenAndMetaByAddressRequest) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenAndMetaByAddressRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type BatchQueryTokenInfoByAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  []string               `protobuf:"bytes,1,rep,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchQueryTokenInfoByAddressRequest) Reset() {
	*x = BatchQueryTokenInfoByAddressRequest{}
	mi := &file_tokenmeta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryTokenInfoByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryTokenInfoByAddressRequest) ProtoMessage() {}

func (x *BatchQueryTokenInfoByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryTokenInfoByAddressRequest.ProtoReflect.Descriptor instead.
func (*BatchQueryTokenInfoByAddressRequest) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{1}
}

func (x *BatchQueryTokenInfoByAddressRequest) GetTokenAddress() []string {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  []byte                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Decimals      int32                  `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Source        int32                  `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TotalSupply   string                 `protobuf:"bytes,6,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	Creator       []byte                 `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
	Icon          string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Uri           string                 `protobuf:"bytes,9,opt,name=uri,proto3" json:"uri,omitempty"`
	MetaData      string                 `protobuf:"bytes,10,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	MetaUpdatedAt string                 `protobuf:"bytes,11,opt,name=meta_updated_at,json=metaUpdatedAt,proto3" json:"meta_updated_at,omitempty"`
	CreationTime  string                 `protobuf:"bytes,12,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	CreateAt      string                 `protobuf:"bytes,13,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt      string                 `protobuf:"bytes,14,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_tokenmeta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{2}
}

func (x *TokenInfo) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *TokenInfo) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenInfo) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *TokenInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenInfo) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *TokenInfo) GetCreator() []byte {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *TokenInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TokenInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *TokenInfo) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

func (x *TokenInfo) GetMetaUpdatedAt() string {
	if x != nil {
		return x.MetaUpdatedAt
	}
	return ""
}

func (x *TokenInfo) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

func (x *TokenInfo) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *TokenInfo) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

type TokenMetaInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TokenId           int64                  `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenAddress      []byte                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	TokenHash         int32                  `protobuf:"varint,3,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	PrimaryPool       []byte                 `protobuf:"bytes,4,opt,name=primary_pool,json=primaryPool,proto3" json:"primary_pool,omitempty"`
	MaxSupply         string                 `protobuf:"bytes,5,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	CirculatingSupply string                 `protobuf:"bytes,6,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	Description       string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	BannerUrl         string                 `protobuf:"bytes,8,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	Twitter           string                 `protobuf:"bytes,9,opt,name=twitter,proto3" json:"twitter,omitempty"`
	Telegram          string                 `protobuf:"bytes,10,opt,name=telegram,proto3" json:"telegram,omitempty"`
	Website           string                 `protobuf:"bytes,11,opt,name=website,proto3" json:"website,omitempty"`
	DexscrAd          int32                  `protobuf:"varint,12,opt,name=dexscr_ad,json=dexscrAd,proto3" json:"dexscr_ad,omitempty"`
	DexscrUpdateLink  int32                  `protobuf:"varint,13,opt,name=dexscr_update_link,json=dexscrUpdateLink,proto3" json:"dexscr_update_link,omitempty"`
	CtoFlag           int32                  `protobuf:"varint,14,opt,name=cto_flag,json=ctoFlag,proto3" json:"cto_flag,omitempty"`
	CreateAt          string                 `protobuf:"bytes,15,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt          string                 `protobuf:"bytes,16,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TokenMetaInfo) Reset() {
	*x = TokenMetaInfo{}
	mi := &file_tokenmeta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMetaInfo) ProtoMessage() {}

func (x *TokenMetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMetaInfo.ProtoReflect.Descriptor instead.
func (*TokenMetaInfo) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{3}
}

func (x *TokenMetaInfo) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *TokenMetaInfo) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *TokenMetaInfo) GetTokenHash() int32 {
	if x != nil {
		return x.TokenHash
	}
	return 0
}

func (x *TokenMetaInfo) GetPrimaryPool() []byte {
	if x != nil {
		return x.PrimaryPool
	}
	return nil
}

func (x *TokenMetaInfo) GetMaxSupply() string {
	if x != nil {
		return x.MaxSupply
	}
	return ""
}

func (x *TokenMetaInfo) GetCirculatingSupply() string {
	if x != nil {
		return x.CirculatingSupply
	}
	return ""
}

func (x *TokenMetaInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TokenMetaInfo) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

func (x *TokenMetaInfo) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

func (x *TokenMetaInfo) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

func (x *TokenMetaInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *TokenMetaInfo) GetDexscrAd() int32 {
	if x != nil {
		return x.DexscrAd
	}
	return 0
}

func (x *TokenMetaInfo) GetDexscrUpdateLink() int32 {
	if x != nil {
		return x.DexscrUpdateLink
	}
	return 0
}

func (x *TokenMetaInfo) GetCtoFlag() int32 {
	if x != nil {
		return x.CtoFlag
	}
	return 0
}

func (x *TokenMetaInfo) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *TokenMetaInfo) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

type GetTokenAndMetaByAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *TokenInfo             `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Meta          *TokenMetaInfo         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenAndMetaByAddressResponse) Reset() {
	*x = GetTokenAndMetaByAddressResponse{}
	mi := &file_tokenmeta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenAndMetaByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenAndMetaByAddressResponse) ProtoMessage() {}

func (x *GetTokenAndMetaByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenAndMetaByAddressResponse.ProtoReflect.Descriptor instead.
func (*GetTokenAndMetaByAddressResponse) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenAndMetaByAddressResponse) GetInfo() *TokenInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *GetTokenAndMetaByAddressResponse) GetMeta() *TokenMetaInfo {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TokenInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TokenInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfoResponse) Reset() {
	*x = TokenInfoResponse{}
	mi := &file_tokenmeta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfoResponse) ProtoMessage() {}

func (x *TokenInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfoResponse.ProtoReflect.Descriptor instead.
func (*TokenInfoResponse) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{5}
}

func (x *TokenInfoResponse) GetList() []*TokenInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type NameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []string               `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameRequest) Reset() {
	*x = NameRequest{}
	mi := &file_tokenmeta_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRequest) ProtoMessage() {}

func (x *NameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRequest.ProtoReflect.Descriptor instead.
func (*NameRequest) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{6}
}

func (x *NameRequest) GetContent() []string {
	if x != nil {
		return x.Content
	}
	return nil
}

type SupplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress  []string               `protobuf:"bytes,1,rep,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyRequest) Reset() {
	*x = SupplyRequest{}
	mi := &file_tokenmeta_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyRequest) ProtoMessage() {}

func (x *SupplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyRequest.ProtoReflect.Descriptor instead.
func (*SupplyRequest) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{7}
}

func (x *SupplyRequest) GetTokenAddress() []string {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

type SupplyInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TokenAddress      []byte                 `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	Symbol            string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals          uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	TotalSupply       string                 `protobuf:"bytes,4,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	MaxSupply         string                 `protobuf:"bytes,5,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	CirculatingSupply string                 `protobuf:"bytes,6,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	Icon              string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	Name              string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SupplyInfo) Reset() {
	*x = SupplyInfo{}
	mi := &file_tokenmeta_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyInfo) ProtoMessage() {}

func (x *SupplyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyInfo.ProtoReflect.Descriptor instead.
func (*SupplyInfo) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{8}
}

func (x *SupplyInfo) GetTokenAddress() []byte {
	if x != nil {
		return x.TokenAddress
	}
	return nil
}

func (x *SupplyInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SupplyInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *SupplyInfo) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

func (x *SupplyInfo) GetMaxSupply() string {
	if x != nil {
		return x.MaxSupply
	}
	return ""
}

func (x *SupplyInfo) GetCirculatingSupply() string {
	if x != nil {
		return x.CirculatingSupply
	}
	return ""
}

func (x *SupplyInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *SupplyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SupplyInfos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*SupplyInfo          `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyInfos) Reset() {
	*x = SupplyInfos{}
	mi := &file_tokenmeta_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyInfos) ProtoMessage() {}

func (x *SupplyInfos) ProtoReflect() protoreflect.Message {
	mi := &file_tokenmeta_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyInfos.ProtoReflect.Descriptor instead.
func (*SupplyInfos) Descriptor() ([]byte, []int) {
	return file_tokenmeta_proto_rawDescGZIP(), []int{9}
}

func (x *SupplyInfos) GetInfos() []*SupplyInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_tokenmeta_proto protoreflect.FileDescriptor

const file_tokenmeta_proto_rawDesc = "" +
	"\n" +
	"\x0ftokenmeta.proto\x12\x02pb\"F\n" +
	"\x1fGetTokenAndMetaByAddressRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\tR\ftokenAddress\"J\n" +
	"#BatchQueryTokenInfoByAddressRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x03(\tR\ftokenAddress\"\x97\x03\n" +
	"\tTokenInfo\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\fR\ftokenAddress\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\x05R\bdecimals\x12\x16\n" +
	"\x06source\x18\x03 \x01(\x05R\x06source\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12!\n" +
	"\ftotal_supply\x18\x06 \x01(\tR\vtotalSupply\x12\x18\n" +
	"\acreator\x18\a \x01(\fR\acreator\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x10\n" +
	"\x03uri\x18\t \x01(\tR\x03uri\x12\x1b\n" +
	"\tmeta_data\x18\n" +
	" \x01(\tR\bmetaData\x12&\n" +
	"\x0fmeta_updated_at\x18\v \x01(\tR\rmetaUpdatedAt\x12#\n" +
	"\rcreation_time\x18\f \x01(\tR\fcreationTime\x12\x1b\n" +
	"\tcreate_at\x18\r \x01(\tR\bcreateAt\x12\x1b\n" +
	"\tupdate_at\x18\x0e \x01(\tR\bupdateAt\"\x90\x04\n" +
	"\rTokenMetaInfo\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\x03R\atokenId\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\fR\ftokenAddress\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x03 \x01(\x05R\ttokenHash\x12!\n" +
	"\fprimary_pool\x18\x04 \x01(\fR\vprimaryPool\x12\x1d\n" +
	"\n" +
	"max_supply\x18\x05 \x01(\tR\tmaxSupply\x12-\n" +
	"\x12circulating_supply\x18\x06 \x01(\tR\x11circulatingSupply\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"banner_url\x18\b \x01(\tR\tbannerUrl\x12\x18\n" +
	"\atwitter\x18\t \x01(\tR\atwitter\x12\x1a\n" +
	"\btelegram\x18\n" +
	" \x01(\tR\btelegram\x12\x18\n" +
	"\awebsite\x18\v \x01(\tR\awebsite\x12\x1b\n" +
	"\tdexscr_ad\x18\f \x01(\x05R\bdexscrAd\x12,\n" +
	"\x12dexscr_update_link\x18\r \x01(\x05R\x10dexscrUpdateLink\x12\x19\n" +
	"\bcto_flag\x18\x0e \x01(\x05R\actoFlag\x12\x1b\n" +
	"\tcreate_at\x18\x0f \x01(\tR\bcreateAt\x12\x1b\n" +
	"\tupdate_at\x18\x10 \x01(\tR\bupdateAt\"l\n" +
	" GetTokenAndMetaByAddressResponse\x12!\n" +
	"\x04info\x18\x01 \x01(\v2\r.pb.TokenInfoR\x04info\x12%\n" +
	"\x04meta\x18\x02 \x01(\v2\x11.pb.TokenMetaInfoR\x04meta\"6\n" +
	"\x11TokenInfoResponse\x12!\n" +
	"\x04list\x18\x01 \x03(\v2\r.pb.TokenInfoR\x04list\"'\n" +
	"\vNameRequest\x12\x18\n" +
	"\acontent\x18\x01 \x03(\tR\acontent\"4\n" +
	"\rSupplyRequest\x12#\n" +
	"\rtoken_address\x18\x01 \x03(\tR\ftokenAddress\"\xfe\x01\n" +
	"\n" +
	"SupplyInfo\x12#\n" +
	"\rtoken_address\x18\x01 \x01(\fR\ftokenAddress\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x04 \x01(\tR\vtotalSupply\x12\x1d\n" +
	"\n" +
	"max_supply\x18\x05 \x01(\tR\tmaxSupply\x12-\n" +
	"\x12circulating_supply\x18\x06 \x01(\tR\x11circulatingSupply\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\"3\n" +
	"\vSupplyInfos\x12$\n" +
	"\x05infos\x18\x01 \x03(\v2\x0e.pb.SupplyInfoR\x05infos2\x90\x02\n" +
	"\bMetadata\x12e\n" +
	"\x18GetTokenAndMetaByAddress\x12#.pb.GetTokenAndMetaByAddressRequest\x1a$.pb.GetTokenAndMetaByAddressResponse\x12^\n" +
	"\x1cBatchQueryTokenInfoByAddress\x12'.pb.BatchQueryTokenInfoByAddressRequest\x1a\x15.pb.TokenInfoResponse\x12=\n" +
	"\x17GetTokenSupplyByAddress\x12\x11.pb.SupplyRequest\x1a\x0f.pb.SupplyInfosB\x15Z\x13dex-stats-sol/pb;pbb\x06proto3"

var (
	file_tokenmeta_proto_rawDescOnce sync.Once
	file_tokenmeta_proto_rawDescData []byte
)

func file_tokenmeta_proto_rawDescGZIP() []byte {
	file_tokenmeta_proto_rawDescOnce.Do(func() {
		file_tokenmeta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tokenmeta_proto_rawDesc), len(file_tokenmeta_proto_rawDesc)))
	})
	return file_tokenmeta_proto_rawDescData
}

var file_tokenmeta_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tokenmeta_proto_goTypes = []any{
	(*GetTokenAndMetaByAddressRequest)(nil),     // 0: pb.GetTokenAndMetaByAddressRequest
	(*BatchQueryTokenInfoByAddressRequest)(nil), // 1: pb.BatchQueryTokenInfoByAddressRequest
	(*TokenInfo)(nil),                           // 2: pb.TokenInfo
	(*TokenMetaInfo)(nil),                       // 3: pb.TokenMetaInfo
	(*GetTokenAndMetaByAddressResponse)(nil),    // 4: pb.GetTokenAndMetaByAddressResponse
	(*TokenInfoResponse)(nil),                   // 5: pb.TokenInfoResponse
	(*NameRequest)(nil),                         // 6: pb.NameRequest
	(*SupplyRequest)(nil),                       // 7: pb.SupplyRequest
	(*SupplyInfo)(nil),                          // 8: pb.SupplyInfo
	(*SupplyInfos)(nil),                         // 9: pb.SupplyInfos
}
var file_tokenmeta_proto_depIdxs = []int32{
	2, // 0: pb.GetTokenAndMetaByAddressResponse.info:type_name -> pb.TokenInfo
	3, // 1: pb.GetTokenAndMetaByAddressResponse.meta:type_name -> pb.TokenMetaInfo
	2, // 2: pb.TokenInfoResponse.list:type_name -> pb.TokenInfo
	8, // 3: pb.SupplyInfos.infos:type_name -> pb.SupplyInfo
	0, // 4: pb.Metadata.GetTokenAndMetaByAddress:input_type -> pb.GetTokenAndMetaByAddressRequest
	1, // 5: pb.Metadata.BatchQueryTokenInfoByAddress:input_type -> pb.BatchQueryTokenInfoByAddressRequest
	7, // 6: pb.Metadata.GetTokenSupplyByAddress:input_type -> pb.SupplyRequest
	4, // 7: pb.Metadata.GetTokenAndMetaByAddress:output_type -> pb.GetTokenAndMetaByAddressResponse
	5, // 8: pb.Metadata.BatchQueryTokenInfoByAddress:output_type -> pb.TokenInfoResponse
	9, // 9: pb.Metadata.GetTokenSupplyByAddress:output_type -> pb.SupplyInfos
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tokenmeta_proto_init() }
func file_tokenmeta_proto_init() {
	if File_tokenmeta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tokenmeta_proto_rawDesc), len(file_tokenmeta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokenmeta_proto_goTypes,
		DependencyIndexes: file_tokenmeta_proto_depIdxs,
		MessageInfos:      file_tokenmeta_proto_msgTypes,
	}.Build()
	File_tokenmeta_proto = out.File
	file_tokenmeta_proto_goTypes = nil
	file_tokenmeta_proto_depIdxs = nil
}
